package backYard;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.testng.annotations.DataProvider;

@CucumberOptions(
        features = "G:/IntelliJWorkspace/cooker-new-version/testdata/backYard.test.feature",
        glue = {"stepDefs"},
       // plugin = {"customReporters.CustomReporter","pretty","json:target/cucumber-reports/output.json"},
        strict = true,
        dryRun = false,
        monochrome = false
)
public class runner extends AbstractTestNGCucumberTests {

    //Created : Fri Apr 24 15:28:35 IST 2020
    //Triggered By : Manjunath

}


//Plugin Created by : Manjunath Prabhakar

// Auto Generated by Cooker Cucumber Maven Plugin